metal_symbols = {
    "alkali_metal": ["Li", "Na", "K", "Rb", "Cs", "Fr"],
    "alkaline_earth_metal": ["Be", "Mg", "Ca", "Sr", "Ba", "Ra"],
    "transition_metal": [
        "Sc",
        "Ti",
        "V",
        "Cr",
        "Mn",
        "Fe",
        "Co",
        "Ni",
        "Cu",
        "Zn",
        "Y",
        "Zr",
        "Nb",
        "Mo",
        "Tc",
        "Ru",
        "Rh",
        "Pd",
        "Ag",
        "Cd",
        "Hf",
        "Ta",
        "W",
        "Re",
        "Os",
        "Ir",
        "Pt",
        "Au",
        "Hg",
        "Lr",
        "Rf",
        "Db",
        "Sg",
        "Bh",
        "Hs",
        "Mt",
        "Ds",
        "Rg",
        "Cn",
    ],
    "metal": ["Al", "Ga", "In", "Sn", "Tl", "Pb", "Bi"],
    "post_transition_metals": ["Nh", "Fl", "Mc", "Lv", "Ts"],
    "metalloid": ["B", "Si", "Ge", "As", "Sb", "Te", "Po"],
    "actinoid": [
        "Ac",
        "Th",
        "Pa",
        "U",
        "Np",
        "Pu",
        "Am",
        "Cm",
        "Bk",
        "Cf",
        "Es",
        "Fm",
        "Md",
        "No",
    ],
    "lanthanoid": [
        "La",
        "Ce",
        "Pr",
        "Nd",
        "Pm",
        "Sm",
        "Eu",
        "Gd",
        "Tb",
        "Dy",
        "Ho",
        "Er",
        "Tm",
        "Yb",
        "Lu",
    ],
}
